### ISSUE TITLE
GUI to Import SQL models & Time Series

### ISSUE THREAD

**Issue by weedkiller** [VelocityDB/VelocityDB#19]
Hello, the GUI from your home page doesn't seem very robust functionality wise or data views.

- [ ] For this to be considered you would need a monitoring/repair/maintenance solution.
- [ ] Is there a data recovery mechanism at the table/object level
- [ ] How would I do Time Series like a PiSoft or Influx
- [ ] How would I do a full text search
- [ ] Do you have data streaming to another instance
- [ ] I like that you have identity in your sample, the store and user manager are not from the latest EF core Identity
- [ ] Can you allow a more unrestricted use of the license 7 days is not feasible or practical. Not even worth investing the time for many dev. it would turn them away. Please see MongoDb and InfluxDB very friendly community licensing, you may get someone who will contribute a better UI for your system

**Comment by VelocityDB** [comment]
Trial license is good for 10 days. You can request additional trial license once it expires. Eventually we request that your purchase a license.

Recovery check and possibly recovery happens in each update transaction. Check for dangling references or corruption can be done with SessionBase.Verify. The verify code is also provided as a sample project.

Time Series are application dependent. You just design your C# classes to what you want, we help you get it efficient if you ask us.

We have a full text search sample. We are using a C# NuGet for the pattern matching. We also provide samples how to do inverted index searches like Google search is using.

Its been a while since I did the Identity implementation, I think you mean for login to web sites. Never saw any intrest in this so not updating. Its all in this GitHub repository.

I have used MongoDB browser, I hate it, nothing to learn, too slow and too much typing required. We provide DatabaseManager that lets you dive into huge amount of data in seconds without any typing of queries required. It also provides a unique tool showing how your data model classes are connected and a VelocityGraph mode for object browsing. Just expand the treeview. For ad hoc queries we use LINQPad. I would love help with samples and GUI tools but we are limited, not spending millions of $ on hype creation, we just provide a high quality product.

Not sure what you mean by streaming to other instances, my guess is with replication. Client keeps replicas in sync in every transaction, servers are also checking with other servers. Usually data is send/read page by page. No client usage so far with replication as far as I know. 

Monitor/repair options could be added. I assume making sure servers are up and responding. Repair is basically never needed. If corruption happens, it's usually a coding issue unique each time with a unique fix that prevents it from happening again. We don't have ongoing issues with corruption like with MongoDB so no tools required to fix indices or other issues.
