### ISSUE TITLE
Velocity with ASP Identity core - multi tenant

### ISSUE THREAD

**Issue by weedkiller** [VelocityDB/VelocityDB#7]
Hi, the charts showing your performance look really good. But seeing only 10 watchers on github over a few yrs was not confidence building. So, I was was looking at information on trying your db with some of the samples. I could not find information on using it - do I need a license and is it free for personal/dev use. If I find its good and I choose to use it in a commercial app where I build web pages/sites then would it be economical and what the pricing would be and are major upgrades included. 

1. I also do not see any multi-tenant sample, is this available/supported like the e.g. with source I pasted below.
2. What is the process to upgrade the DB, /roll back the DB
3. Does it work with MVC CORE on linux as well
4. How are _FK relationships managed_ (this is not easy to understand from your docs, how to navigate, retrieve, update Master-Detail tables etc, give that its in native C#, this could also be one of your most powerful features if the syntax chaining is done easily), and is it consistent and ACID compliant?
5. Whats the road map on whats planned next
6. Are the CRUD operations pessimistic concurrent
7. Is there a concept of roll back
8. Is it possible to repair or look at damaged records for e.g. what if someone unhooks the machine while a write is happen - who do you recover from it.

Multi tenant code Samples here [1](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant) with this 

- class [modification](https://github.com/JSkimming/AspNet.Identity.EntityFramework.Multitenant/blob/master/src/AspNet.Identity.EntityFramework.Multitenant/MultitenantUserStore.Generic.cs)
- [Also here](https://github.com/joeaudette/cloudscribe)
- Via [nhinate e.g.](https://github.com/nhibernate/NHibernate.AspNet.Identity)

Thanks

**Comment by VelocityDB** [comment]
Hi there, yes our GitHub repository isn't very popular. Might be because it is easier and better packaged in the download available from https://velocitydb.com/Download.aspx. 
Our ASP.NET Identity driver has not been updated for multi tenant support but it should be a simple to do update. Our src for the driver is availabe here. You should be able to find answers to your other questions in the User's Guide https://velocitydb.com/UserGuide.aspx.
Recovery is built into the architecture, if updates made by a transaction does not completly make it to disk then all updates made by the failing transaction is undone. Transaction tracking is recorded in database 0, 0.odb. Better support for referential integrity is planned in R6, coming up soon. You can request features, we do what our user's request. License cost is $200 - $6000 depending on what you need. .NET Core is supported but have not been tested with Linux yet. You can generate free 10 day trial licenses yourself at https://velocitydb.com/Secure/license.aspx

**Comment by weedkiller** [comment]
Hi thanks for the answers.

Its challenging with so many OSS DB's out there, but to get some traction to build a user base, you may have to give away a free chunk 1GB or less storage for free or something along those lines.

There is an effort to make some of the pricing flexible, its still not a practical usage scenario for someone dev/small business to invest in this DB, till you build up a large enough user base one thats vested and has developed their products on your velocityDb, you may need to revisit that model & tools to manage both the DB and data underneath.

So, in one of the frameworks I am using, I suggested that [they look at your db here](http://bit.ly/2hpPeDT) if you have a chance you should post a snippet there once people get curious.

Also, did you see the latest [VS Magazine article](http://bit.ly/2hBs8L1).

Hope this helps

**Comment by VelocityDB** [comment]
VelocityDB comes with a LinqPad driver and a WPF Database Manager for visualizing data. Both are open source in the [download](https://velocitydb.com/Download.aspx) and in this GitHub repository.
Thanks for your post. A web based visualizer would be nice, There are a couple for graph tools (.js) that can be used which we mention in our [User's Guide](https://velocitydb.com/UserGuide.aspx). 

Limiting license by DB size is a possible way we may consider doing sometime. We know we have a superior database engine. We hope people will discover this but it is a slow process without spending millions on marketing like others are doing. It is still encouaging that we have been able to get clients around the world paying between $200 and $400 for a license. So far from 23 different countries. The only way we can become more popular is by having our existing user's spread the word. I appreciate you all.
