### ISSUE TITLE
Compile and build issues and missing files

### ISSUE THREAD

**Issue by mach37** [VelocityDB/VelocityDB#8]
Hello,

I am trying this, but I could not get it compile - I am wondering what all is needed to run a sample app - the wiki page is empty. I decided to give it a shot with some free time.. 

![image](https://cloud.githubusercontent.com/assets/12221440/22577362/2e0ccff8-e98f-11e6-8362-69a8786ae3ac.png)

The issue maybe, many errors on locating files.

`Severity	Code	Description	Project	File	Line	Suppression State`

`Error		Unable to locate 'C:\Samples\VelocityDB-master\.nuget\nuget.exe'	VelocityDbSchema	`

**Comment by VelocityDB** [comment]
Thanks for spending some time with VelocityDB and reporting these build issues. They should now be fixed in this Git repository. The same src is also part of the [download](https://velocitydb.com/Download.aspx) 
and take a look at the [User's Guide](https://velocitydb.com/UserGuide.aspx)

**Comment by mach37** [comment]
Hey thanks... I'll check it out later this weekend, on my free time - what is the simplest/easiest foot print to run and test. i.e. which projects are the bare minimum? 

If I want to test 10 objects, with _Joins/Saves and Queries_ (Foreign Keys between them) most common stuff, which sample should I follow. Once I wrap my head around how you do things in the VDB basics it should be easier to follow for me.

To me, there seem to be _2 options on RDB/relationships_, where I could use the graph edges/vertices or the Virtual Collection Reference like EF - in the help this choice and which one to pick when is not obvious to me. I am guess this may have something to do at an instance level vs object class modelling level, is that correct?

In the documentation it mentions I need inherit my objects from your base object, but I have another base object in place already. _Wouldn't this be easier?_ with a slight different design using generic/templates like `VDB.Save<Car, Driver>(myCar, familyDrivers);`  how are the foreign key's and the updating/persistence of dependent table data.

One vital feature I did not find and would like to suggest is an Auto **Auditing** or shadow persist all transactions performed/log history of the user action, and being able to archive/truncate or move chunks to a .bak file. When registering my objects for persisting I would like to setup the option to also Audit, user logins like success, fails, Ip, what he visited from etc.


I like the simplicity of the concept to persist objects natively, the ability to subscribe to update and that you have GraphJSON support natively, this seems like it gives the users a nice view of things to come. 

regards
Mach

**Comment by VelocityDB** [comment]
The bare minimum is the NuGet VelocityDB that contains VelocityDB.dll.
If you are intrested in the VelocityGraph extension then look at any of the samples for that, otherwise start with Sample1 and work your way to more complex samples.
Your classes don't have to inherit from OptimizedPersistent, you can also implement IOptimizedPersistent interface, ISerializable or persist without interface implementation or base class. As name suggests persisting with OptimizedPersistent base class is more efficient than with no interface as object ID and object Page references aren't accessable from such object. In such cases a waek dictionary is used to lookup objects based on ID which is an extra cost.
Foreign keys are just C# object references or references by object ID. Most objects will get an 64bit object id.
There is no built in user tracking, we do track what each update transaction is doing on a high level in database 0.

Sounds like you may come up with some fresh new ideas, I can't wait to hear them!
