### ISSUE TITLE
VelocityDB with ASP MVC 4.52 Identity 2.1 without EF

### ISSUE THREAD

**Issue by mach37** [VelocityDB/VelocityDB#9]
Hey,  I just got an idea 💡 and wanted to let you know _(after looking at your website performance charts), this DB may have significant advantage in the case of ASP identity_.

If you gut the EF entity framework in your ASP MVC Identity Example , and also 

- [x] since you do not need dapper (no ORM)
- [ ] since you do not need EF [no new code, _just gut it_!!](https://blog.markjohnson.io/exorcising-entity-framework-from-asp-net-identity/) 
- [x] since you are not making any SP calls

Then redo the performance tests with 200 simultaneous/parallel logins, updates etc  and share those results I bet that would make a great impression on the developer community!!

Thanks

**Comment by VelocityDB** [comment]
Yes that is a good idea. However, VelocityDB has not been great for performance of small update transactions. Release 6.0.8 reduces the update transaction overhead so it is improving.
EF is already out of our ASP MVC Identity driver and its sample, not sure where you saw it references?

**Comment by mach37** [comment]
Sorry if I confused the issue, before I explain, the solution _still does not build form Github_ - I try to work on this on the weekends, its frustrating when it does not build.

I am working on a sample to  run Identity without EF. Because, your framework makes the EF useless, the true speed benefit of velocity is the native operations in C# persistence, which is a plus 💯 !

So, when I saw your sample it includes EF, which only adds bloat I am trying to remove it to make a case on why we should switch (EF was designed for convenience when working with Relation Tabular DB _**to translate from C# to SQL**_). EF adds 4x to 6x overhead from the [Dapper benchmarks](https://www.exceptionnotfound.net/dapper-vs-entity-framework-vs-ado-net-performance-benchmarking/) page - many benefits are lost in using EF. Since ASP identity is bundled by default and used by many, (unfortunately with EF) and many complain on the speed EF, if you provided a second variant in your sample without EF, so people could work directly with linq or natively with the objects it would showcase speed and convenience.

Does not build!
[![a21940ae-f149-11e6-9e80-5da3be2eb44d.png](https://s21.postimg.org/5flztmnwn/a21940ae_f149_11e6_9e80_5da3be2eb44d.png)](https://postimg.org/image/o7xux7kar/)

**Comment by VelocityDB** [comment]
About the build issues. I did an update but I now see that the [Sync Framework Nuget](https://www.nuget.org/packages/Microsoft.SyncFramework/) doesn't completly install all that is required on package restore. May have to install https://www.microsoft.com/en-us/download/details.aspx?id=23217
Also LinqPad driver build require that you install LinqPad and follow the build instruction in our text file.
I am not sure how to solve the Sync Framework requirement, with our InstallShield installer we can probably add it to the installer but for GitHub we may require you to install Sync Framework first since the Nuget appears not to make it happen automaticly, any ideas?

As I said, we do not include EF in our Asp MSC Identify driver. There are still some packages related to identify that are required but not packages like Microsoft.AspNet.Identity.EntityFramework. We have other project uses EF but not the ones related to our Asp MSC Identify driver (VelocityDBExtensions2 and AspNetIdentitySample).

I agree EF is slow and a great comparison for VelocityDB. Dapper is much better if you stay within SQL world. Not sure simple login stuff is the best way to show the strength of VelocityDB vs Entity Framework (EF) usage but it might be a start. I imagine a more complex scenario with EF maight be a better comparison, what do you think?
